name: Semgrep SAST Scan

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: self-hosted
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci
