name: Semgrep SAST Scan

on:
  push:
    branches:
      - main

jobs:
  semgrep-scan:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile Java Project
      run: |
        mvn clean compile

    - name: Install Python and pip3
      run: |
        sudo apt update
        sudo apt install python3-pip python3-venv -y

    - name: Run Semgrep Scan
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}  
      run: |
        python3 -m venv semgrep-env
        semgrep-env/bin/pip install semgrep
        semgrep-env/bin/semgrep ci
